site_name: Loose Lab
site_url: https://looselab.github.io/

repo_name: LooseLab
repo_url: https://github.com/LooseLab
edit_uri: ''  #disables edit button

theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.tabs.sticky
    
plugins:
  - blog
  - search
  - tags

nav:
  - index.md
  - research.md
  - people.md
  - media.md
  - Blog:
    - blog/index.md
  - contact.md

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  